version: '3.7'

services:
  app:
    container_name: app_container
    build:
      context: .
      dockerfile: ./Dockerfile
      target: builder
    volumes:
      - ./:/app
    ports:
      - "9999:9999"
      - "40000:40000"
    environment:
      PGPASSWORD: test
    tty: true
    depends_on: 
      - db

  db:
    container_name: db_container
    image: postgres:11
    ports:
      - "5432:5432"
    environment: 
      TZ: Asia/Tokyo
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: sample_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./containers/postgres:/docker-entrypoint-initdb.d

  web:
    container_name: nginx_container
    build: containers/nginx
    volumes:
      - ./public:/www/public
      - ./logs:/var/log/nginx
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8080:80 
    depends_on:
      - app